apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | b64enc }}